name: ilastik_napari_26_2
channels:
  - ilastik-forge
  - conda-forge
dependencies:
  - napari
  - pyqt
  - fastfilters
  - rasterio
  - pip
  - pip:
      - spatialdata
      - napari-spatialdata
      - git+https://github.com/saeyslab/harpy.git
