{% set setup = load_setup_py_data() %}

package:
  name: napari-ilastik
  version: {{ setup.version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python>=3.7
    - setuptools>=61
    - setuptools-scm>=6.4
  run:
    - fastfilters
    - importlib-metadata
    - napari
    - numpy
    - qtpy
    - scikit-learn
    - sparse

about:
  home: https://github.com/ilastik/napari-ilastik
  license: MIT
  summary: ilastik plugin for napari
